const data = [
  {
    id: 1,
    name: '',
    source: require('./image1.jpeg'),
    width: 809,
    height: 455,
  },
  {
    id: 2,
    name: '',
    source: require('./image2.jpeg'),
    width: 960,
    height: 685,
  },
  {
    id: 3,
    name: '',
    source: require('./image3.jpeg'),
    width: 596,
    height: 390,
  },
  {
    id: 4,
    name: '',
    source: require('./image4.jpeg'),
    width: 800,
    height: 473,
  },
  {
    id: 5,
    name: '',
    source: require('./image5.jpeg'),
    width: 600,
    height: 395,
  },
  {
    id: 6,
    name: '',
    source: require('./image6.jpeg'),
    width: 1600,
    height: 1067,
  },
  {
    id: 7,
    name: '',
    source: require('./image7.jpeg'),
    width: 660,
    height: 409,
  },
  {
    id: 8,
    name: '',
    source: require('./image8.jpeg'),
    width: 1024,
    height: 768,
  },
  {
    id: 9,
    name: '',
    source: require('./image9.jpeg'),
    width: 500,
    height: 300,
  },
  {
    id: 10,
    name: '',
    source: require('./image10.jpeg'),
    width: 400,
    height: 250,
  },
  {
    id: 11,
    name: '',
    source: require('./image11.jpeg'),
    width: 1600,
    height: 1000,
  },
  {
    id: 12,
    name: '',
    source: require('./image12.jpeg'),
    width: 604,
    height: 451,
  },
  {
    id: 13,
    name: '',
    source: require('./image13.jpeg'),
    width: 1024,
    height: 768,
  },
  {
    id: 14,
    name: '',
    source: require('./image14.jpeg'),
    width: 1280,
    height: 720,
  },
  {
    id: 15,
    name: '',
    source: require('./image15.jpeg'),
    width: 660,
    height: 371,
  },
  {
    id: 16,
    name: '',
    source: require('./image16.jpeg'),
    width: 1000,
    height: 673,
  },
  {
    id: 17,
    name: '',
    source: require('./image17.jpeg'),
    width: 660,
    height: 409,
  },
  {
    id: 18,
    name: '',
    source: require('./image18.jpeg'),
    width: 1280,
    height: 720,
  },
  {
    id: 19,
    name: '',
    source: require('./image19.jpeg'),
    width: 600,
    height: 371,
  },
  {
    id: 20,
    name: '',
    source: require('./image20.jpeg'),
    width: 650,
    height: 433,
  },
]

export default data
